name: Workflow

on:
  push:
    branches: [yummy]
  pull_request:
    branches: [yummy]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: "latest"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Type Check
        run: pnpm run typeCheck

      - name: Lint
        run: pnpm run format

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build

      - name: Publish
        if: github.ref == 'refs/heads/yummy'
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            LARK_WEBHOOK
            LARK_SIGN_SECRET
            GH_WEBHOOK_SECRET
        env:
          LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
          LARK_SIGN_SECRET: ${{ secrets.LARK_SIGN_SECRET }}
          GH_WEBHOOK_SECRET: ${{ secrets.GH_WEBHOOK_SECRET }}
          # "CF_ACCOUNT_ID"  is deprecated. Please use "CLOUDFLARE_ACCOUNT_ID", instead.
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID || secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
